
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: Z2xydC0ydTNnZ25CZE1jNnRmNW1mWHAyWC1XODZNUXB3T2pJS2REb3pDblU2TVE4LjAxLjE3MWFoYjAxcA==
  runner-token: ""
